name: mc_scrollable_calendar
version: 1.5.0
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  scrollable_positioned_list: ^0.3.8
  # sliding_sheet2:
  #   path: custom_libs/sliding_sheet2
  # sliding_sheet2:
  #   git: https://github.com/gidrokolbaska/sliding_sheet2.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
